getProductOptionByProductIdAndOptionId:
  handler: src/productOption/lambda/ProductOption.getByProductIdAndOptionIdHandler
  events:
    - http:
        method: GET
        path: /api/products/{productId}/options/{id}
        cors: true

getProductOptionsByProductId:
  handler: src/productOption/lambda/ProductOption.getByProductIdHandler
  events:
    - http:
        method: GET
        path: /api/products/{productId}/options/
        cors: true

createProductOption:
  handler: src/productOption/lambda/ProductOption.createHandler
  events:
    - http:
        method: POST
        path: /api/products/{productId}/options
        cors: true
