Resources:
  ProductOptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-ProductOption
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
        - AttributeName: optionId
          KeyType: RANGE  
      AttributeDefinitions:
        - AttributeName: optionId
          AttributeType: S
        - AttributeName: productId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.dynamoDbTableReadThroughPut}
        WriteCapacityUnits: ${self:custom.dynamoDbTableWriteThroughPut}