getProductById:
  handler: src/product/lambda/Product.getByIdHandler
  events:
    - http:
        method: GET
        path: /api/products/{id}
        cors: true

createProduct:
  handler: src/product/lambda/Product.createHandler
  events:
    - http:
        method: POST
        path: /api/products
        cors: true
