getProductById:
  handler: src/product/lambda/Product.getByIdHandler
  events:
    - http:
        method: GET
        path: /api/products/{productId}

getProduct:
  handler: src/product/lambda/Product.getHandler
  events:
    - http:
        method: GET
        path: /api/products        

createProduct:
  handler: src/product/lambda/Product.createHandler
  events:
    - http:
        method: POST
        path: /api/products

updateProduct:
  handler: src/product/lambda/Product.updateHandler
  events:
    - http:
        method: PUT
        path: /api/products/{productId}

deleteProduct:
  handler: src/product/lambda/Product.deleteHandler
  events:
    - http:
        method: DELETE
        path: /api/products/{productId}        