Resources:
  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-Product      
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.dynamoDbTableReadThroughPut}
        WriteCapacityUnits: ${self:custom.dynamoDbTableWriteThroughPut}